### ISSUE TITLE
bug: relative symlinks are not handled properly

### ISSUE THREAD

**Issue by ernado** [go-faster/portoshim#7]
```yml
apiVersion: v1
kind: Pod
metadata:
  name: symlink-test
spec:
  containers:
    - name: alma
      image: almalinux:9.2
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      imagePullPolicy: IfNotPresent
    - name: ubuntu
      image: ubuntu:latest
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
```bash
kubectl apply -f https://raw.githubusercontent.com/go-faster/ytst/main/symlink-test.yml
```

Porto:
```console
root@ub1:~/ytst# kubectl exec -i -t symlink-test --container alma -- ls -lah /var/run/secrets
ls: cannot access '/var/run/secrets': No such file or directory
root@ub1:~/ytst# kubectl exec -i -t symlink-test --container ubuntu -- ls -lah /var/run/secrets
total 12K
drwxrwxr-x 3 root root 4.0K Feb 27 18:28 .
drwxr-xr-x 1 root root 4.0K Feb 27 18:28 ..
drwxrwxr-x 3 root root 4.0K Feb 27 18:28 kubernetes.io
```

Containerd:
```console
ernado@work:/src/faster/ytst$ kubectl exec -i -t symlink-test --container alma -- ls -lah /var/run/secrets
total 12K
drwxr-xr-x 3 root root 4.0K Feb 27 18:27 .
drwxr-xr-x 1 root root 4.0K Feb 27 18:27 ..
drwxr-xr-x 3 root root 4.0K Feb 27 18:27 kubernetes.io
ernado@work:/src/faster/ytst$ kubectl exec -i -t symlink-test --container ubuntu -- ls -lah /var/run/secrets
total 12K
drwxr-xr-x 3 root root 4.0K Feb 27 18:27 .
drwxr-xr-x 1 root root 4.0K Feb 27 18:27 ..
drwxr-xr-x 3 root root 4.0K Feb 27 18:27 kubernetes.i
```
